# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NoteForCode' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for NoteForCode
  pod 'YYKit', '~> 1.0.9'
  pod 'AFNetworking', '~> 3.1.0'
end
